on: [push]
jobs:
  critic:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Run Perl::Critic
      uses: natanlao/perl-critic-action@v1.1
      with:
        files: critic
